# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: scotfree
service: pomodorify

provider:
  name: aws
  runtime: python3.9
  region: us-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    SPOTIFY_CLIENT_ID: ${ssm:/pomodorify/${self:provider.stage}/SPOTIFY_CLIENT_ID}
    SPOTIFY_CLIENT_SECRET: ${ssm:/pomodorify/${self:provider.stage}/SPOTIFY_CLIENT_SECRET}
    SPOTIFY_REDIRECT_URI: ${ssm:/pomodorify/${self:provider.stage}/SPOTIFY_REDIRECT_URI}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
          Resource:
            - arn:aws:ssm:${self:provider.region}:*:parameter/pomodorify/${self:provider.stage}/*
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 
            - 'arn:aws:logs:${self:provider.region}:*:log-group:/aws/lambda/*'

functions:
  api:
    handler: backend.wsgi_handler.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
    package:
      individually: true
      patterns:
        - '!venv/**'
        - '!__pycache__/**'
        - '!.git/**'
        - '!.env'
        - '!.gitignore'
        - '!README.md'
        - '!node_modules/**'
        - '!package*.json'
        - '!serverless.yml'
        - '!deployment.zip'
        - 'backend/**'
        - 'requirements.txt'
        - 'wsgi_handler.py'
        - 'venv/lib/python3.9/site-packages/markupsafe/**'

custom:
  wsgi:
    app: backend.handler.app
    packRequirements: true
    pythonBin: python3.9
    useRequirements: true
    packRequirementsZip: true

plugins:
  - serverless-wsgi

